# fly.toml app configuration file generated for mortgagemate-backend on 2025-10-29T23:34:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mortgagemate-backend'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile.prod'

[env]
  NODE_ENV = 'production'
  PORT = '4321'

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
